fix(notebook): put id column as str and explain density representation
octopize/avatar-python pull request #106
Opened 2024-03-27 17:13 UTC by albanfelix

Related to #2236

2024-03-27 17:14 UTC, albanfelix commented on notebooks/Tutorial9-Multitable.py
>  #       format_name: light
Tuto 9 modifications are just `lint-fix`

2024-03-28 08:54 UTC, olivierabz requested changes
The explanations and figures are really clear but I believe they should go in the doc (https://docs.octopize.io/docs/understanding/geolocation_privacy_assessment) rather than the notebook.

2024-03-28 08:54 UTC, olivierabz commented on notebooks/Tutorial10_Geolocation_privacy_assessment.py
> +# ![Density representation of Porto' traces£](img/porto_density.png)
I actually think that we should not include png here but something generated from the data. This has more its place in the doc (https://docs.octopize.io/docs/understanding/geolocation_privacy_assessment)

2024-03-28 09:02 UTC, olivierabz commented on notebooks/Tutorial10_Geolocation_privacy_assessment.py
> +selected_id = "id1"
Also I disagree with this. We should not have to change the data file. We need to go and fix the ID handling, for sure we'll get numeric IDs in practice.

2024-06-11 10:09 UTC, closed without merging