docs: reorganise client doc
octopize/avatar-python pull request #43
Opened 2023-01-25 15:31 UTC by jpetot

I also update the python client. But my main work was to re-organize the client doc. 
see the picture to have an overview of the tree 😁
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/48205834/214604884-c6ec57a9-e225-4770-bbe5-44e77a9ce56a.png">

2023-01-25 16:04 UTC, tcrasset reviewed
Very nice, this is a step forward to making the doc easier to read and use! Good job.

I just have some general comments:
- do we want to keep writing in `.md` or `.rst` (we can use either one, we have `pandoc` to switch between them). Personally, I find the former to have easier syntax to write:
	- no double backticks to have a variable,
	- no forcing to have the same number of characters for the underline of the title,
	- not a different character for different title size
	- no complicated syntax to have a code block
- you have split the `tutorial.md` notebook, which was fully tested with `make test-integration`
We'll have to make sure that any code we write in the `.rst` file is fully tested, perhaps we can use the same mechanism as we did for `tutorial.md`
We'll also have to make sure to use the tutorials in `notebooks/` as our integration test then, and run `make test-tutorial` instead of `make test-integration` everytime.

- Now that you've taken the time to split the different sections, shouldn't we reflect on what our file structure should be like? I feel like `how_to.rst` will become the new `tutorial.rst`, a big file with lots of unrelated parts.

2023-01-25 16:06 UTC, tas17 reviewed
The new looking is way better IMO. But to me everything should be tested so that it remains up to date. It's not the case anymore.

2023-01-25 16:06 UTC, tas17 commented on doc/source/how_to.rst
> +   <!-- It is python, just doing this so that test-integration does not run this code (need mail config to run)  -->
If it's rst, it's not tested anymore. so javascript -> python and remove the comment

2023-01-25 16:06 UTC, tas17 commented on doc/source/how_to.rst
> +.. code:: javascript
Same here

2023-01-30 16:41 UTC, tas17 approved these changes

2023-01-31 07:51 UTC, tcrasset requested changes
Good, some fixes I'd like to see because they are out of date. Some are just nitpicks

2023-01-31 07:51 UTC, tcrasset commented on .github/workflows/lci.yaml
> +        run: make doc-fast
```suggestion
      - name: Build latest doc version
        run: make doc-fast
```

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +## How to log in to the doc/source/user_guide.md server
What is the `doc/source/user_guide.md` server?

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +## How to upload a dataframe
```suggestion
## How to upload a data
```
You are wanting to expose how data is uploaded, both as a dataframe, and as a csv. So the title has to be generic

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +as a ``.csv`` file
```suggestion
### As a `.csv` file
```
double backticks are for `.rst`

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +You can lunch an avatarization with some simple privacy and signal metrics.
```suggestion
You can launch an avatarization with some simple privacy and signal metrics.
```

ctrl + F 'lunch' at this point

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +You can launch a privacy metrics with two datasets, the original and the anonymized.
```suggestion
You can launch a privacy metrics job with two datasets, the original and the anonymized.
```

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +You need to run privacy and signal metrics with the arguments ``persistance_job_id=job.id`` before running the report.
```suggestion
```
This is not true anymore

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +See [processors](processors.html) for more information about the processor.
```suggestion
See [processors](processors.html) for more information about the processors. 
```

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +As a pandas dataframe.
```suggestion
### As a pandas dataframe
```

2023-01-31 07:51 UTC, tcrasset commented on doc/source/user_guide.md
> +As a ``.csv`` file as string.
```suggestion
### As a `.csv` formatted string
```

2023-01-31 08:25 UTC, merged