feat: add batch functions and tutorial
octopize/avatar-python pull request #67
Opened 2023-05-26 09:38 UTC by jpetot

- feat(api): add batch functions and tutorial
- feat(api): add function to split and download batch
- feat(api): polish tutorial and split functions

2023-05-26 12:58 UTC, jpetot commented on notebooks/Tutorial7-Batch_avatarization.py
> +# # TODO: add a schema of the process
you are right, it's now done

2023-05-29 10:19 UTC, tcrasset requested changes

2023-05-29 10:19 UTC, tcrasset commented on avatars/api_test.py
> +    client.pandas_integration.download_dataframe.side_effect = [train, split]
The following isn't really the scope of this PR, but we should take most of the stuff that was setup for `integration_test` in the `avatar` repo and copy it here, e.g. the `client` fixture in `conftest.py` that was used to authenticate the client, and mock it, etc..

Then, you wouldn't have to mock the whole `client` but only `download_dataframe` with `unittest.mock.patch`

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +            maximum number of row by batch, this parameter determine the number of batch that will be created
```suggestion
            maximum number of rows per batch, this parameter determines the number of batches that will be created
```

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +            splits: all other batches
```suggestion

        splits: all other batches
```

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +    number_of_split = math.ceil(len(df) / row_limit)
```suggestion
    number_of_splits = math.ceil(len(df) / row_limit)
```
nit

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +            "your own batch pipeline."
```suggestion
            "You can increase your `row_limit`, reduce your categorical variability, or build "
            "your own batch pipeline."
```

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +    values: Dict[str, Dict[str, bool]] = {col: {} for col in df.columns}
docstring

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +    df_array = np.array(df)
You are duplicating memory. Use `df.values` or `df.to_numpy()`

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +                should_keep_row = True
Small comment explaining what is done?

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +                should_keep_row = True
```suggestion
                values[df.columns[j]][df_array[i, j]] = True
                should_keep_row = True
                break
```

2023-05-29 10:19 UTC, tcrasset commented on avatars/lib/split.py
> +                should_keep_row = True
Once you find the first unique value, you can break and add the row.

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +warnings.filterwarnings("ignore")
Why?

We should fix the warnings.

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +warnings.filterwarnings("ignore")
This shouldn't be in public documentation, shows bad practice from our part

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +
```suggestion
df = pd.read_csv("../fixtures/adult_with_missing.csv").head(1000)

```

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +RowLimit = 200
```suggestion
row_limit = 200
```
`snake_case` for python variables

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +dataset_ref_id, dataset_splited_ids, order = upload_batch_and_get_order(
```suggestion
dataset_training_id, dataset_splited_ids, order = upload_batch_and_get_order(
```

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +dataset_ref_id, dataset_splited_ids, order = upload_batch_and_get_order(
```suggestion
dataset_ref_id, dataset_split_ids, order = upload_batch_and_get_order(
```
same as above

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +batch_job = client.jobs.get_avatarization_batch_job(batch_job.id, timeout=10000)
```suggestion
# -

batch_job = client.jobs.get_avatarization_batch_job(batch_job.id, timeout=10000)
```
nit: only one get

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +# you can access to worst metric over all batches
```suggestion
# you can access the worst metrics over all batches
```

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +# ## Built the anonymized dataset
```suggestion
# ## Build the anonymized dataset
```

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +signal_job_ref = client.jobs.create_signal_metrics_batch_job(
```suggestion
signal_job_training = client.jobs.create_signal_metrics_batch_job(
```

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +# ### Get the shuflle avatar dataframe
```suggestion
# ### Get the shuffled avatar dataframe
```

2023-05-29 10:19 UTC, tcrasset commented on notebooks/Tutorial7-Batch_avatarization.py
> +# ###  Get the sensitive unshuffle avatar dataframe
```suggestion
# ###  Get the sensitive unshuffled avatar dataframe
```

2023-05-29 10:20 UTC, tcrasset commented on avatars/api.py
> +    """Download shuffled avatar from batch result.
*the shuffled

2023-05-30 14:12 UTC, tcrasset requested changes
Very close to merging, mainly want the `DEFAULT_TIMEOUT` to be used, and strongly advise using pytest fixtures.

2023-05-30 14:12 UTC, tcrasset commented on avatars/api.py
> +    timeout: int = 10,
```suggestion
    timeout: int = DEFAULT_TIMEOUT,
```
I think there is a variable called like this, either in `api.py` or `client.py`

2023-05-30 14:12 UTC, tcrasset commented on avatars/api.py
> +            Api client
Arguments needs reordering to match the function definition

2023-05-30 14:12 UTC, tcrasset commented on avatars/api_test.py
> +)
I still think we should use pytest fixtures, there are no downsides

2023-05-30 14:12 UTC, tcrasset commented on avatars/lib/split.py
> +            "your own batch pipeline."
still there, `built` is past participle, we want the present

2023-05-30 14:12 UTC, tcrasset commented on doc/source/avatars/processors.DatetimeProcessor.rst
> +   :members:@
Typo?

2023-05-31 09:29 UTC, merged